### ISSUE TITLE
Trip meter value not showing

### ISSUE THREAD

**Issue by mountainbikert** [leeyuentuen/polestar_api#100]
Hi guys, 
I installed 1.6.0 and my trip meter (huidige kilometerstand) is showing unknown (onbekend). Huidige trip meter is also showing unknown.

**Comment by leeyuentuen** [comment]
maybe check the log, maybe the value is too high due fault on polestar data

**Comment by leeyuentuen** [comment]
@mountainbikert can you take a look in it?

**Comment by mountainbikert** [comment]
After a couple of hours it was showing the value again in the correct format.
