### ISSUE TITLE
No cars found in account Exception

### ISSUE THREAD

**Issue by Cruguah** [leeyuentuen/polestar_api#105]
Hello,

First of all, thanks for the Polestar integration for HA.

I have installed the integration via HACS and am trying to log in with my Polestar account. According to the plugin, the account information is correct, but a car associated with this account cannot be found.
The car is not linked to my account because I am not the owner of the car, the car is owned by the lease company.

Would it be possible to reintroduce the VIN number solution for users who cannot own the car, for example lease drivers?

Thanks for all the hard work.

Yours sincerely,
Cruguah

**Comment by stijnpieters** [comment]
incidentally, similar/same to issue I opened earlier https://github.com/leeyuentuen/polestar_api/issues/104#issue-2094661421

**Comment by leeyuentuen** [comment]
normally if lease company is the owner you still can have a full access account. just ask polestar for transfer

btw duplicate issue
https://github.com/leeyuentuen/polestar_api/issues/90

**Comment by Cruguah** [comment]
I called customer support and they resolved the issue, so problem solved and happy Polestar owner and Home Assistant user!

Thanks for your support!
