### ISSUE TITLE
Unable to use all parameters in automation

### ISSUE THREAD

**Issue by RobDemandt** [leeyuentuen/polestar_api#106]
Some of the parameters provided, mainly the ones that do not contain numerical values, can be used in Home Assistant automations.

Example:
Would like to build an automation to alert me when the car has been charged. I can create an automation and set an initial variable of battery level (the system gives me an above and below field), 

<img width="1289" alt="Screenshot 2024-01-23 at 15 00 51" src="https://github.com/leeyuentuen/polestar_api/assets/33842717/f3fd720d-9534-4e94-9c26-93829e1f7c04">

but when I want to set an additional (and) variable for charge cable status (which van be connected or not connected), there is no way to select these options and the system trows an error.

<img width="1100" alt="Screenshot 2024-01-23 at 15 01 34" src="https://github.com/leeyuentuen/polestar_api/assets/33842717/9b7773bc-a72d-4c70-9e05-c817134783a8">

<img width="564" alt="Screenshot 2024-01-23 at 15 01 55" src="https://github.com/leeyuentuen/polestar_api/assets/33842717/6f397090-0b9e-4521-874a-5f5e0717a103">

**Comment by leeyuentuen** [comment]
i'll take a look on it

**Comment by RobDemandt** [comment]
I tested with using the entity instead of device and can confirm this is indeed working, thanks for the hint.

Reasoning for this additional if statement in the automation is to prevent situations  when the API times out or is not available whilst the charging happens and then trowing the notification at a random moment whilst driving with a charge of above 80%. Had this already happen a couple of times with the unreliable Polestar backend/connectivity. Now it should at least not do this when there is no cable connected.
