### ISSUE TITLE
The 'charger connection status' has no history in Home Assistant.

### ISSUE THREAD

**Issue by VdR1960** [leeyuentuen/polestar_api#107]
The 'charger connection status' sensor has no history 'No statistics found' in Home Assistant:

![Screenshot 2024-01-25 141247](https://github.com/leeyuentuen/polestar_api/assets/76566363/9ebe3430-a8b5-4907-ab13-54fae2b596f0)

Would expect to see similar as for 'charging status' sensor:

![Screenshot 2024-01-25 141501](https://github.com/leeyuentuen/polestar_api/assets/76566363/5350fb0c-4d89-4547-b5bc-80bda38ffb79)

Is it because the sensor is defined as measurement? state_class: measurement?

![Screenshot 2024-01-25 135423](https://github.com/leeyuentuen/polestar_api/assets/76566363/19eb8f99-9b75-4e0b-9a62-b13bfaa75795)

**Comment by leeyuentuen** [comment]
it could be from measurement. i can remove them later and let you try.

**Comment by mroussel** [comment]
Same issue here.

**Comment by mroussel** [comment]
It works now. Thank you.
