### ISSUE TITLE
Can not add repository

### ISSUE THREAD

**Issue by ultradumme** [leeyuentuen/polestar_api#108]
Hello,
I am not able to add the repository of the Polestar_API.
I get this warning: "https://github.com/leeyuentuen/polestar_api is not a valid add-on repository"
Can somebody help me?

kind regards,
Sander

**Comment by leeyuentuen** [comment]
can you make a screenshot of the error? maybe you have add space before or after the URL?

**Comment by ultradumme** [comment]
Hi, 
screenshot in attachment. 
There was no space before or after the URL... 



Van: "Tuen Lee" ***@***.***> 
Aan: "leeyuentuen/polestar_api" ***@***.***> 
Cc: "sander dumont" ***@***.***>, "Author" ***@***.***> 
Verzonden: Donderdag 1 februari 2024 16:18:31 
Onderwerp: Re: [leeyuentuen/polestar_api] Can not add repository (Issue #108) 





can you make a screenshot of the error? maybe you have add space before or after the URL?

**Comment by leeyuentuen** [comment]
i didn't see you screenshot, but should be this?
![image](https://github.com/leeyuentuen/polestar_api/assets/1487966/6149cbb2-da4e-4f2b-bd30-4c09414ae057)

**Comment by leeyuentuen** [comment]
you have use system add-on store instead on hacs repo I think

**Comment by ultradumme** [comment]
I tried to add the repository this way; 
homeassistant dashboard -> settings -> add-ons -> add-on store -> repositories -> 
paste "https://github.com/leeyuentuen/polestar_api" -> add 

then I get the error notification. 
The way of adding is correct, right? 


Van: "Tuen Lee" ***@***.***> 
Aan: "leeyuentuen" ***@***.***> 
Cc: "sander dumont" ***@***.***>, "State change" ***@***.***> 
Verzonden: Donderdag 1 februari 2024 16:45:38 
Onderwerp: Re: [leeyuentuen/polestar_api] Can not add repository (Issue #108) 





you have use system add-on store instead on hacs repo I think
