### ISSUE TITLE
Average consumption does not display decimals

### ISSUE THREAD

**Issue by jkkataja** [leeyuentuen/polestar_api#111]
Hi,

It appears that we see values without decimals. I forgot to check from the Polestar app if it displays those, before resetting the TM counters, but it does appear to have the .0 present there at the moment.

Any chance we can get decimals displayed also?

Thanks

**Comment by Trnquill** [comment]
Polestar app seems to always show ".0". It's not added precision, it's just added UI clutter. The value from the API seems to be integer, not decimal.

**Comment by jkkataja** [comment]
Apparently that will be fixed in the future, I suspect nothing needs to be done here:

![image](https://github.com/leeyuentuen/polestar_api/assets/42151530/111b2196-fa8b-4539-bbee-27ba764adcd6)

**Comment by leeyuentuen** [comment]
i think this has been fixed at polestar side?
![image](https://github.com/leeyuentuen/polestar_api/assets/1487966/d016c605-145d-490c-9e35-aeac49ff07ba)

**Comment by jkkataja** [comment]
Yup, looks like this got fixed with P3.0.3 -> closing issue 👍
