### ISSUE TITLE
Feature request: Position, door lock state, climate timer on/off, charge start/stop

### ISSUE THREAD

**Issue by kp-bit** [leeyuentuen/polestar_api#119]
Don't know how much of this is possible, but the following are pretty much must haves and they are exposed in the app:

- Car position
- Doors locked/unlocked status (or even the possibility to toggle)
- Turn the automatic climate timer on/off (or even change time)
- Charge start/stop

Hoping many more features will come!

**Comment by leeyuentuen** [comment]
duplicated https://github.com/leeyuentuen/polestar_api/discussions/114

is more discussion then issue
