### ISSUE TITLE
multiple vehicles

### ISSUE THREAD

**Issue by stephanlarsson** [leeyuentuen/polestar_api#128]
I have two cars. I can only get one to load all the entities, but the other just loads the image.

**Comment by leeyuentuen** [comment]
good issue, but i need to find a way to add one extra car in the portal to test xD

**Comment by preeefix** [comment]
Let me know what requests you need and I can drop exports from Polestar US.

**Comment by marky5525** [comment]
I second that.
I ordered my P4 and the car is produced. Now I have two cars in my account, unfortunately the data is shown from the new car, somewhere parked in china :)

What can I do to help? You need any data?

**Comment by leeyuentuen** [comment]
If there is a trust in me and I can use one of your account to test them (send them over email), I'll take a try,

normally I have only access on the webportal (to see the data)  but I don't have access to unlock/find location of your car)

**Comment by pckahrs** [comment]
I also experienced this issue after my ordered PS4 got a VIN and was added to the Polestar site. In order to get data for my PS2 back to Home Assistant I edited this line: https://github.com/leeyuentuen/polestar_api/blob/4a13cc57363e840ddb985a59c77941cbb1a31632/custom_components/polestar_api/pypolestar/polestar.py#L126
to this:
`                'data': result['data'][CAR_INFO_DATA][1], 'timestamp': datetime.now()}`

**Comment by leeyuentuen** [comment]
> I also experienced this issue after my ordered PS4 got a VIN and was added to the Polestar site. In order to get data for my PS2 back to Home Assistant I edited this line:
> 
> https://github.com/leeyuentuen/polestar_api/blob/4a13cc57363e840ddb985a59c77941cbb1a31632/custom_components/polestar_api/pypolestar/polestar.py#L126
> 
> 
> to this:
> ` 'data': result['data'][CAR_INFO_DATA][1], 'timestamp': datetime.now()}`

if you use this, you still get one car, but only the other one. but it should something like that to change

**Comment by preeefix** [comment]
Although not comfortable to share the credentials, are there any particular requests that you'd like to see the results from?

**Comment by leeyuentuen** [comment]
see this thread:
https://github.com/leeyuentuen/polestar_api/issues/150
