### ISSUE TITLE
Integration pulling 2 months old data

### ISSUE THREAD

**Issue by kp-bit** [leeyuentuen/polestar_api#139]
Suddenly today, the integration has started pulling data from 2 months ago. Token expiration looks ok and I've tried both reloading the integration and restarting HA. Anyone else experiencing this?

![polestar](https://github.com/leeyuentuen/polestar_api/assets/61055573/8576bf13-f2e3-4918-9692-735092a2fd74)

**Comment by motionist** [comment]
Have similar issue
Suddenly odometer shows negative growth in distance traveled
![Screenshot_2024-05-13-20-27-45-06_c3a231c25ed346e59462e84656a70e50](https://github.com/leeyuentuen/polestar_api/assets/62009560/f60f1fc5-bdc9-4ba3-8a46-78d117d3d485)
![Screenshot_2024-05-13-20-28-26-49_4340b2429be81a0b24f71d6e160ae8de](https://github.com/leeyuentuen/polestar_api/assets/62009560/d170be90-1662-45a4-b156-481a35166ff9)

**Comment by JoeRimo** [comment]
Same issue with 2 month old data. 
Also is showing my car is charging while it's sitting in my office parking lot not doing that.
![image](https://github.com/leeyuentuen/polestar_api/assets/65092769/806c3a7b-8633-408f-b8d7-ea2d1e01816d)

**Comment by 3shirts** [comment]
Same problem here. Dropped 4000km just over 3 hours ago.

**Comment by wouterhardeman** [comment]
I also experienced this today, but values are now normal again. I think this is something on Polestar's side.

My **guess** is that it might have something to do with the P3.0.3 update that was reverted and they are doing some data recovery/migration/rollback to prepare for a new release.

**Comment by kp-bit** [comment]
Not really buying the rollback theory, mine was back to correct battery update time and thus SOC yesterday but this morning, everything is 2 months old again.

**Comment by leeyuentuen** [comment]
check on this page to see if the odometer is the same?
https://www.polestar.com/uk/login/cars

i get the value from that website, the value that you post are from the polestar app, this use a another api call.

could be that polestar has rollback/restore data and still didn't update data from the car?

**Comment by leeyuentuen** [comment]
for me, it look like it is a bug of polestar?

![Screenshot_2024-05-14-14-45-25-47_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/leeyuentuen/polestar_api/assets/1487966/09565170-76e3-4e6b-b274-1d104615999a)
![Screenshot_2024-05-14-14-45-31-19_c3a231c25ed346e59462e84656a70e50](https://github.com/leeyuentuen/polestar_api/assets/1487966/7c89a9e9-b82c-4119-aae2-445b772350cf)

**Comment by kp-bit** [comment]
My data on that website is 2 months old but data in the app is correct.

**Comment by kp-bit** [comment]
All my data look correct now, so apparently a backend issue... Closing issue.

**Comment by leeyuentuen** [comment]
i'll keep this open due the issue is still exist

**Comment by TotalGriffLock** [comment]
Just to confirm I also see this behaviour. Correct value in the app, incorrect on the website and in the HA integration. Definitely an issue at Polestar

**Comment by wouterhardeman** [comment]
Everything seems to be back to normal for me today. Out of curiosity, I'm wondering if those who are still experiencing issues might be running the P3.0.3 version of the Polestar software? As for myself, I'm currently on P2.14.3.
