### ISSUE TITLE
Cannot login 

### ISSUE THREAD

**Issue by supersonical** [leeyuentuen/polestar_api#15]
Logger: custom_components.polestar_api.config_flow
Source: custom_components/polestar_api/config_flow.py:47
Integration: polestar_api ([documentation](https://github.com/leeyuentuen/polestar_api))
First occurred: 12:44:51 AM (3 occurrences)
Last logged: 12:48:23 AM

Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/config_flow.py", line 47, in _create_device
    await device.init()
  File "/config/custom_components/polestar_api/polestar_api.py", line 51, in init
    'data': result['data']['getConsumerCarsV2'][0], 'timestamp': datetime.now()}
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by leeyuentuen** [comment]
have you installed polestar api before? (clean install of polestar api or upgrade)
maybe give me more debug log

**Comment by leeyuentuen** [comment]
@supersonical

**Comment by supersonical** [comment]
Still the same error after redownloading the in HACS? 

<img width="478" alt="image" src="https://github.com/leeyuentuen/polestar_api/assets/33106083/fe0f9f18-4448-4afc-afab-ffb5e813989d">

**Comment by leeyuentuen** [comment]
try to remove the configured polestar_api and log in with your  polestar credential (before it was using volvo development credential)

https://github.com/leeyuentuen/polestar_api#fill-the-information

**Comment by supersonical** [comment]
> have you installed polestar api before? (clean install of polestar api or upgrade) maybe give me more debug log

Download the full logs from Home assistant but their is no more details of the error. How do i turn on debug for the integration?

2023-12-20 10:22:06.290 ERROR (MainThread) [custom_components.polestar_api.config_flow] Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/config_flow.py", line 47, in _create_device
    await device.init()
  File "/config/custom_components/polestar_api/polestar_api.py", line 51, in init
    'data': result['data']['getConsumerCarsV2'][0], 'timestamp': datetime.now()}
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by supersonical** [comment]
> try to remove the configured polestar_api and log in with your polestar credential (before it was using volvo development credential)
> 
> https://github.com/leeyuentuen/polestar_api#fill-the-information

I have tried to login and know for sure my credentials work, or did i miss understand you?

**Comment by supersonical** [comment]
Should i maybe go backa version where it uses the Volvo Dev?

**Comment by leeyuentuen** [comment]
you can login in this site?
https://polestarid.eu.polestar.com/PolestarLogin/login and you can see your car located there?

**Comment by leeyuentuen** [comment]
> Should i maybe go backa version where it uses the Volvo Dev?

the volvo dev doesn't work anymore on polestar car

**Comment by supersonical** [comment]
> you can login in this site? https://polestarid.eu.polestar.com/PolestarLogin/login and you can see your car located there?

Hmm that is maybe the problem, the car is not located their, due to my partner is the "Owner" of the car. She can se it on that page. Let me try it with her account.

**Comment by supersonical** [comment]
This is so weird! if i login with her account on www.polestar.com i can see the car and the battery status. 
But when i login to "https://polestarid.eu.polestar.com/PolestarLogin/login" i can only see here acount details but not the car. 
Is it possible that the issue with that the car is a leasing? 

Below info is when i login to Polestar.com
<img width="1533" alt="Skärmavbild 2023-12-20 kl  10 53 27" src="https://github.com/leeyuentuen/polestar_api/assets/33106083/d2ec365b-c20f-4046-aaff-6c500de78070">

**Comment by leeyuentuen** [comment]
i gave the wrong url. should be this one:

https://polestarid.eu.polestar.com/as/authorization.oauth2?response_type=code&client_id=polmystar&redirect_uri=https%3A%2F%2Fwww.polestar.com%2Fsign-in-callback&scope=openid%20profile%20email%20customer:attributes%20customer:attributes:write

**Comment by leeyuentuen** [comment]
@supersonical  still got the issue?

**Comment by supersonical** [comment]
Weird, now it just worked. So no, its fixed now and i got it in now. :)
