### ISSUE TITLE
Support for Australia?

### ISSUE THREAD

**Issue by ginoputrino** [leeyuentuen/polestar_api#152]
Hi,
even though I have a polestar ID and credentials which work with the android phone polestar app, when I try to integrate this into my home assistant, I receive the error:

 [custom_components.polestar_api.pypolestar.polestar] No cars found in account

According to https://developer.volvocars.com/apis/connected-vehicle/v2/overview/ Volvo does not provide support for their API for cars outside of Europe / Middle East / Africa.

Is this situation the same for Polestar? Or is there a perhaps a different API url for the Australia/Asia Pacific region. 

I see that in pypolestar, urls are hard-coded e.g.: https://pc-api.polestar.com/eu-north-1/auth/
and I am hoping there are a similar but different ones for Australia that someone might know about.

**Comment by leeyuentuen** [comment]
i'm  not using volvo developer api
https://github.com/leeyuentuen/polestar_api/issues/9


should be the same issue here:
https://github.com/leeyuentuen/polestar_api/issues/90

**Comment by ginoputrino** [comment]
Thanks.
Yes, this is the same issue as #90
