### ISSUE TITLE
where to change password of polestar id?

### ISSUE THREAD

**Issue by Rubinski78** [leeyuentuen/polestar_api#153]
Hi,

Maybe a stupid question but I changed the password of my polestar id and cannot find a wat to reconfigure this into the API.
I can’t find the screen where you can fill in the username, password and VIN (like shown in the documentation).
Can anyone give me the golden tip? 😅

thanks!

**Comment by leeyuentuen** [comment]
not supported yet, only remove the entity and readd them

**Comment by Rubinski78** [comment]
I'm sorry, I closed this issue by accident.
