### ISSUE TITLE
GraphQL: cannot query field

### ISSUE THREAD

**Issue by taskinen** [leeyuentuen/polestar_api#154]
I started getting the following error couple of hours ago. Every entity in the integration just turned "Unavailable" without warning, and the following error appears in logs:

```
This error originated from a custom integration.

Logger: custom_components.polestar_api
Source: custom_components/polestar_api/__init__.py:45
integration: Polestar API (documentation)
First occurred: 14:54:36 (3 occurrences)
Last logged: 15:55:55

API Exception on update data Get GraphQL error: {"errors":[{"message":"Cannot query field \"belongsToFleet\" on type \"VehicleInformation\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"belongsToFleet\" on type \"VehicleInformation\"."," at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)"," at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)"," at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)"," at CTr (/var/task/src/functions/gateway/handler.js:48:24240)"," at c1r (/var/task/src/functions/gateway/handler.js:79:60144)"," at f (/var/task/src/functions/gateway/handler.js:287:40654)"," at zLr (/var/task/src/functions/gateway/handler.js:287:38973)"," at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"," at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}},{"message":"Cannot query field \"hardware\" on type \"VehicleInformation\". Did you mean \"software\"?","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"hardware\" on type \"VehicleInformation\". Did you mean \"software\"?"," at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)"," at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)"," at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)"," at CTr (/var/task/src/functions/gateway/handler.js:48:24240)"," at c1r (/var/task/src/functions/gateway/handler.js:79:60144)"," at f (/var/task/src/functions/gateway/handler.js:287:40654)"," at zLr (/var/task/src/functions/gateway/handler.js:287:38973)"," at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"," at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}},{"message":"Cannot query field \"claims\" on type \"VehicleInformation\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"claims\" on type \"VehicleInformation\"."," at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)"," at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)"," at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)"," at CTr (/var/task/src/functions/gateway/handler.js:48:24240)"," at c1r (/var/task/src/functions/gateway/handler.js:79:60144)"," at f (/var/task/src/functions/gateway/handler.js:287:40654)"," at zLr (/var/task/src/functions/gateway/handler.js:287:38973)"," at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"," at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}},{"message":"Cannot query field \"performedClaims\" on type \"VehicleInformation\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"performedClaims\" on type \"VehicleInformation\"."," at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)"," at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)"," at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)"," at CTr (/var/task/src/functions/gateway/handler.js:48:24240)"," at c1r (/var/task/src/functions/gateway/handler.js:79:60144)"," at f (/var/task/src/functions/gateway/handler.js:287:40654)"," at zLr (/var/task/src/functions/gateway/handler.js:287:38973)"," at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"," at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}}]}
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/__init__.py", line 45, in async_setup_entry
    await polestar.init()
  File "/config/custom_components/polestar_api/polestar.py", line 35, in init
    await self.polestarApi.init()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 48, in init
    await self._get_vehicle_data()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 117, in _get_vehicle_data
    result = await self.get_graph_ql(params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 201, in get_graph_ql
    raise PolestarApiException(f"Get GraphQL error: {result.text}")
custom_components.polestar_api.pypolestar.exception.PolestarApiException: Get GraphQL error: {"errors":[{"message":"Cannot query field \"belongsToFleet\" on type \"VehicleInformation\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"belongsToFleet\" on type \"VehicleInformation\".","    at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)","    at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)","    at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)","    at CTr (/var/task/src/functions/gateway/handler.js:48:24240)","    at c1r (/var/task/src/functions/gateway/handler.js:79:60144)","    at f (/var/task/src/functions/gateway/handler.js:287:40654)","    at zLr (/var/task/src/functions/gateway/handler.js:287:38973)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}},{"message":"Cannot query field \"hardware\" on type \"VehicleInformation\". Did you mean \"software\"?","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"hardware\" on type \"VehicleInformation\". Did you mean \"software\"?","    at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)","    at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)","    at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)","    at CTr (/var/task/src/functions/gateway/handler.js:48:24240)","    at c1r (/var/task/src/functions/gateway/handler.js:79:60144)","    at f (/var/task/src/functions/gateway/handler.js:287:40654)","    at zLr (/var/task/src/functions/gateway/handler.js:287:38973)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}},{"message":"Cannot query field \"claims\" on type \"VehicleInformation\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"claims\" on type \"VehicleInformation\".","    at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)","    at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)","    at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)","    at CTr (/var/task/src/functions/gateway/handler.js:48:24240)","    at c1r (/var/task/src/functions/gateway/handler.js:79:60144)","    at f (/var/task/src/functions/gateway/handler.js:287:40654)","    at zLr (/var/task/src/functions/gateway/handler.js:287:38973)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}},{"message":"Cannot query field \"performedClaims\" on type \"VehicleInformation\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"performedClaims\" on type \"VehicleInformation\".","    at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)","    at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)","    at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)","    at CTr (/var/task/src/functions/gateway/handler.js:48:24240)","    at c1r (/var/task/src/functions/gateway/handler.js:79:60144)","    at f (/var/task/src/functions/gateway/handler.js:287:40654)","    at zLr (/var/task/src/functions/gateway/handler.js:287:38973)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}}]}
```

If I try to remove the integration and add it again, I get a generic "Unexpected error creating api." and the following error in logs:

```
This error originated from a custom integration.

Logger: custom_components.polestar_api.config_flow
Source: custom_components/polestar_api/config_flow.py:43
integration: Polestar API (documentation)
First occurred: 16:26:12 (2 occurrences)
Last logged: 16:35:37

Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/config_flow.py", line 43, in _create_device
    await device.init()
  File "/config/custom_components/polestar_api/polestar.py", line 35, in init
    await self.polestarApi.init()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 48, in init
    await self._get_vehicle_data()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 117, in _get_vehicle_data
    result = await self.get_graph_ql(params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 201, in get_graph_ql
    raise PolestarApiException(f"Get GraphQL error: {result.text}")
custom_components.polestar_api.pypolestar.exception.PolestarApiException: Get GraphQL error: {"errors":[{"message":"Cannot query field \"belongsToFleet\" on type \"VehicleInformation\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"belongsToFleet\" on type \"VehicleInformation\".","    at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)","    at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)","    at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)","    at CTr (/var/task/src/functions/gateway/handler.js:48:24240)","    at c1r (/var/task/src/functions/gateway/handler.js:79:60144)","    at f (/var/task/src/functions/gateway/handler.js:287:40654)","    at zLr (/var/task/src/functions/gateway/handler.js:287:38973)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}},{"message":"Cannot query field \"hardware\" on type \"VehicleInformation\". Did you mean \"software\"?","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"hardware\" on type \"VehicleInformation\". Did you mean \"software\"?","    at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)","    at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)","    at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)","    at CTr (/var/task/src/functions/gateway/handler.js:48:24240)","    at c1r (/var/task/src/functions/gateway/handler.js:79:60144)","    at f (/var/task/src/functions/gateway/handler.js:287:40654)","    at zLr (/var/task/src/functions/gateway/handler.js:287:38973)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}},{"message":"Cannot query field \"claims\" on type \"VehicleInformation\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"claims\" on type \"VehicleInformation\".","    at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)","    at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)","    at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)","    at CTr (/var/task/src/functions/gateway/handler.js:48:24240)","    at c1r (/var/task/src/functions/gateway/handler.js:79:60144)","    at f (/var/task/src/functions/gateway/handler.js:287:40654)","    at zLr (/var/task/src/functions/gateway/handler.js:287:38973)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}},{"message":"Cannot query field \"performedClaims\" on type \"VehicleInformation\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"performedClaims\" on type \"VehicleInformation\".","    at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)","    at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)","    at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)","    at CTr (/var/task/src/functions/gateway/handler.js:48:24240)","    at c1r (/var/task/src/functions/gateway/handler.js:79:60144)","    at f (/var/task/src/functions/gateway/handler.js:287:40654)","    at zLr (/var/task/src/functions/gateway/handler.js:287:38973)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}}]}
```

The username and password is validated correctly, because if I enter incorrect password I get an error about invalid authentication.

**Comment by kdhoe85** [comment]
Same issue

**Comment by motionist** [comment]
Same issue 
Could likely be a change to the API

**Comment by shucky69** [comment]
Same issue here. Got this straight after a Home assistant core update to 2024.9.2. Working fine before.

**Comment by mchuk** [comment]
Same for me too, also after updating the home assistant core

**Comment by han-alink** [comment]
Same issue, also after reinstalling

**Comment by seagull2000** [comment]
I also have this issue.  I have updated HA core too but I also noticed that Polestar App needed to log in again with some new features so I'm thinking an API change has occurred.

**Comment by leeyuentuen** [comment]
i'm just release an update, let me check if that is working

**Comment by kdhoe85** [comment]
> i'm just release an update, let me check if that is working

You last version made it work again. Thx!

**Comment by seagull2000** [comment]
> I also have this issue. I have updated HA core too but I also noticed that Polestar App needed to log in again with some new features so I'm thinking an API change has occurred.

Fixed for me too! Thank you!

**Comment by motionist** [comment]
That resolved it. 
Thx for speedy resolution

**Comment by shucky69** [comment]
Fixed thanks. Wish Polestar were as fast.

**Comment by Birdman86** [comment]
Didn't do much for me.
Still getting errors...

**Comment by leeyuentuen** [comment]
> Didn't do much for me. Still getting errors...

what for error?

**Comment by Birdman86** [comment]
```
API Exception on update data Cannot return null for non-nullable field WorkOrder.status.
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/__init__.py", line 45, in async_setup_entry
    await polestar.init()
  File "/config/custom_components/polestar_api/polestar.py", line 35, in init
    await self.polestarApi.init()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 47, in init
    await self._get_vehicle_data()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 119, in _get_vehicle_data
    result = await self.get_graph_ql(params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 218, in get_graph_ql
    raise PolestarApiException(error_message)
custom_components.polestar_api.pypolestar.exception.PolestarApiException: Cannot return null for non-nullable field WorkOrder.status.
```

`[{'message': 'Cannot return null for non-nullable field WorkOrder.status.', 'path': ['getConsumerCarsV2', 0, 'serviceHistory', 0, 'status'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'stacktrace': ['Error: Cannot return null for non-nullable field WorkOrder.status.', ' at ow (/var/task/src/functions/mystar/handler.js:83:5905)', ' at B8e (/var/task/src/functions/mystar/handler.js:83:5270)', ' at n9 (/var/task/src/functions/mystar/handler.js:83:4784)', ' at Dde (/var/task/src/functions/mystar/handler.js:83:8691)', ' at ow (/var/task/src/functions/mystar/handler.js:83:6202)', ' at /var/task/src/functions/mystar/handler.js:83:6630', ' at Function.from (<anonymous>)', ' at Gkr (/var/task/src/functions/mystar/handler.js:83:6515)', ' at ow (/var/task/src/functions/mystar/handler.js:83:6060)', ' at B8e (/var/task/src/functions/mystar/handler.js:83:5270)', ' at n9 (/var/task/src/functions/mystar/handler.js:83:4784)', ' at Dde (/var/task/src/functions/mystar/handler.js:83:8691)', ' at ow (/var/task/src/functions/mystar/handler.js:83:6202)', ' at ow (/var/task/src/functions/mystar/handler.js:83:5864)', ' at /var/task/src/functions/mystar/handler.js:83:6630', ' at Function.from (<anonymous>)'], 'message': 'Cannot return null for non-nullable field WorkOrder.status.', 'locations': [{'line': 1, 'column': 435}], 'path': ['getConsumerCarsV2', 0, 'serviceHistory', 0, 'status']}, 'serviceName': 'mystar'}}, {'message': 'Cannot return null for non-nullable field WorkOrder.status.', 'path': ['getConsumerCarsV2', 0, 'serviceHistory', 1, 'status'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'stacktrace': ['Error: Cannot return null for non-nullable field WorkOrder.status.', ' at ow (/var/task/src/functions/mystar/handler.js:83:5905)', ' at B8e (/var/task/src/functions/mystar/handler.js:83:5270)', ' at n9 (/var/task/src/functions/mystar/handler.js:83:4784)', ' at Dde (/var/task/src/functions/mystar/handler.js:83:8691)', ' at ow (/var/task/src/functions/mystar/handler.js:83:6202)', ' at /var/task/src/functions/mystar/handler.js:83:6630', ' at Function.from (<anonymous>)', ' at Gkr (/var/task/src/functions/mystar/handler.js:83:6515)', ' at ow (/var/task/src/functions/mystar/handler.js:83:6060)', ' at B8e (/var/task/src/functions/mystar/handler.js:83:5270)', ' at n9 (/var/task/src/functions/mystar/handler.js:83:4784)', ' at Dde (/var/task/src/functions/mystar/handler.js:83:8691)', ' at ow (/var/task/src/functions/mystar/handler.js:83:6202)', ' at ow (/var/task/src/functions/mystar/handler.js:83:5864)', ' at /var/task/src/functions/mystar/handler.js:83:6630', ' at Function.from (<anonymous>)'], 'message': 'Cannot return null for non-nullable field WorkOrder.status.', 'locations': [{'line': 1, 'column': 435}], 'path': ['getConsumerCarsV2', 0, 'serviceHistory', 1, 'status']}, 'serviceName': 'mystar'}}, {'message': 'Cannot return null for non-nullable field WorkOrder.status.', 'path': ['getConsumerCarsV2', 0, 'serviceHistory', 2, 'status'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'stacktrace': ['Error: Cannot return null for non-nullable field WorkOrder.status.', ' at ow (/var/task/src/functions/mystar/handler.js:83:5905)', ' at B8e (/var/task/src/functions/mystar/handler.js:83:5270)', ' at n9 (/var/task/src/functions/mystar/handler.js:83:4784)', ' at Dde (/var/task/src/functions/mystar/handler.js:83:8691)', ' at ow (/var/task/src/functions/mystar/handler.js:83:6202)', ' at /var/task/src/functions/mystar/handler.js:83:6630', ' at Function.from (<anonymous>)', ' at Gkr (/var/task/src/functions/mystar/handler.js:83:6515)', ' at ow (/var/task/src/functions/mystar/handler.js:83:6060)', ' at B8e (/var/task/src/functions/mystar/handler.js:83:5270)', ' at n9 (/var/task/src/functions/mystar/handler.js:83:4784)', ' at Dde (/var/task/src/functions/mystar/handler.js:83:8691)', ' at ow (/var/task/src/functions/mystar/handler.js:83:6202)', ' at ow (/var/task/src/functions/mystar/handler.js:83:5864)', ' at /var/task/src/functions/mystar/handler.js:83:6630', ' at Function.from (<anonymous>)'], 'message': 'Cannot return null for non-nullable field WorkOrder.status.', 'locations': [{'line': 1, 'column': 435}], 'path': ['getConsumerCarsV2', 0, 'serviceHistory', 2, 'status']}, 'serviceName': 'mystar'}}, {'message': 'Cannot return null for non-nullable field WorkOrder.status.', 'path': ['getConsumerCarsV2', 0, 'serviceHistory', 3, 'status'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'stacktrace': ['Error: Cannot return null for non-nullable field WorkOrder.status.', ' at ow (/var/task/src/functions/mystar/handler.js:83:5905)', ' at B8e (/var/task/src/functions/mystar/handler.js:83:5270)', ' at n9 (/var/task/src/functions/mystar/handler.js:83:4784)', ' at Dde (/var/task/src/functions/mystar/handler.js:83:8691)', ' at ow (/var/task/src/functions/mystar/handler.js:83:6202)', ' at /var/task/src/functions/mystar/handler.js:83:6630', ' at Function.from (<anonymous>)', ' at Gkr (/var/task/src/functions/mystar/handler.js:83:6515)', ' at ow (/var/task/src/functions/mystar/handler.js:83:6060)', ' at B8e (/var/task/src/functions/mystar/handler.js:83:5270)', ' at n9 (/var/task/src/functions/mystar/handler.js:83:4784)', ' at Dde (/var/task/src/functions/mystar/handler.js:83:8691)', ' at ow (/var/task/src/functions/mystar/handler.js:83:6202)', ' at ow (/var/task/src/functions/mystar/handler.js:83:5864)', ' at /var/task/src/functions/mystar/handler.js:83:6630', ' at Function.from (<anonymous>)'], 'message': 'Cannot return null for non-nullable field WorkOrder.status.', 'locations': [{'line': 1, 'column': 435}], 'path': ['getConsumerCarsV2', 0, 'serviceHistory', 3, 'status']}, 'serviceName': 'mystar'}}, {'message': 'Cannot return null for non-nullable field WorkOrder.status.', 'path': ['getConsumerCarsV2', 0, 'serviceHistory', 4, 'status'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'stacktrace': ['Error: Cannot return null for non-nullable field WorkOrder.status.', ' at ow (/var/task/src/functions/mystar/handler.js:83:5905)', ' at B8e (/var/task/src/functions/mystar/handler.js:83:5270)', ' at n9 (/var/task/src/functions/mystar/handler.js:83:4784)', ' at Dde (/var/task/src/functions/mystar/handler.js:83:8691)', ' at ow (/var/task/src/functions/mystar/handler.js:83:6202)', ' at /var/task/src/functions/mystar/handler.js:83:6630', ' at Function.from (<anonymous>)', ' at Gkr (/var/task/src/functions/mystar/handler.js:83:6515)', ' at ow (/var/task/src/functions/mystar/handler.js:83:6060)', ' at B8e (/var/task/src/functions/mystar/handler.js:83:5270)', ' at n9 (/var/task/src/functions/mystar/handler.js:83:4784)', ' at Dde (/var/task/src/functions/mystar/handler.js:83:8691)', ' at ow (/var/task/src/functions/mystar/handler.js:83:6202)', ' at ow (/var/task/src/functions/mystar/handler.js:83:5864)', ' at /var/task/src/functions/mystar/handler.js:83:6630', ' at Function.from (<anonymous>)'], 'message': 'Cannot return null for non-nullable field WorkOrder.status.', 'locations': [{'line': 1, 'column': 435}], 'path': ['getConsumerCarsV2', 0, 'serviceHistory', 4, 'status']}, 'serviceName': 'mystar'}}]`

**Comment by leeyuentuen** [comment]
@Birdman86 can you check this?
https://github.com/leeyuentuen/polestar_api/releases/tag/1.6.15

**Comment by Birdman86** [comment]
@leeyuentuen 
That fixed it.
Nice work!
Thank you!

**Comment by taskinen** [comment]
Can confirm 1.6.15 fixed my original issue. I have now added the integration again and all entities show valid values now.

Thank you @leeyuentuen so much for a quick fix! I hope I could help with this custom component in the future.
