### ISSUE TITLE
App does not initialize anymore after updating to latest HA Core on 24 sept 2024

### ISSUE THREAD

**Issue by SnokxStefan** [leeyuentuen/polestar_api#158]
The application worked fine for more than a year, now after upgrading to latest HA Core, the app does not initialize anymore.

I would be great if you could solve this ( however you dont own a polestar anymore ;-)

Logger: custom_components.polestar_api
Source: custom_components/polestar_api/__init__.py:45
integration: Polestar API ([documentation](https://github.com/leeyuentuen/polestar_api))
First occurred: 21:37:09 (2 occurrences)
Last logged: 21:40:58

API Exception on update data Get GraphQL error: {"errors":[{"message":"Cannot query field \"belongsToFleet\" on type \"VehicleInformation\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"belongsToFleet\" on type \"VehicleInformation\"."," at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)"," at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)"," at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)"," at CTr (/var/task/src/functions/gateway/handler.js:48:24240)"," at c1r (/var/task/src/functions/gateway/handler.js:79:60144)"," at f (/var/task/src/functions/gateway/handler.js:287:40654)"," at zLr (/var/task/src/functions/gateway/handler.js:287:38973)"," at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"," at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}},{"message":"Cannot query field \"hardware\" on type \"VehicleInformation\". Did you mean \"software\"?","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"hardware\" on type \"VehicleInformation\". Did you mean \"software\"?"," at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)"," at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)"," at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)"," at CTr (/var/task/src/functions/gateway/handler.js:48:24240)"," at c1r (/var/task/src/functions/gateway/handler.js:79:60144)"," at f (/var/task/src/functions/gateway/handler.js:287:40654)"," at zLr (/var/task/src/functions/gateway/handler.js:287:38973)"," at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"," at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}},{"message":"Cannot query field \"claims\" on type \"VehicleInformation\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"claims\" on type \"VehicleInformation\"."," at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)"," at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)"," at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)"," at CTr (/var/task/src/functions/gateway/handler.js:48:24240)"," at c1r (/var/task/src/functions/gateway/handler.js:79:60144)"," at f (/var/task/src/functions/gateway/handler.js:287:40654)"," at zLr (/var/task/src/functions/gateway/handler.js:287:38973)"," at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"," at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}},{"message":"Cannot query field \"performedClaims\" on type \"VehicleInformation\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"performedClaims\" on type \"VehicleInformation\"."," at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)"," at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)"," at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)"," at CTr (/var/task/src/functions/gateway/handler.js:48:24240)"," at c1r (/var/task/src/functions/gateway/handler.js:79:60144)"," at f (/var/task/src/functions/gateway/handler.js:287:40654)"," at zLr (/var/task/src/functions/gateway/handler.js:287:38973)"," at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"," at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}}]}
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/__init__.py", line 45, in async_setup_entry
    await polestar.init()
  File "/config/custom_components/polestar_api/polestar.py", line 35, in init
    await self.polestarApi.init()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 40, in init
    await self._get_vehicle_data()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 109, in _get_vehicle_data
    result = await self.get_graph_ql(params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 185, in get_graph_ql
    raise PolestarApiException(f"Get GraphQL error: {result.text}")
custom_components.polestar_api.pypolestar.exception.PolestarApiException: Get GraphQL error: {"errors":[{"message":"Cannot query field \"belongsToFleet\" on type \"VehicleInformation\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"belongsToFleet\" on type \"VehicleInformation\".","    at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)","    at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)","    at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)","    at CTr (/var/task/src/functions/gateway/handler.js:48:24240)","    at c1r (/var/task/src/functions/gateway/handler.js:79:60144)","    at f (/var/task/src/functions/gateway/handler.js:287:40654)","    at zLr (/var/task/src/functions/gateway/handler.js:287:38973)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}},{"message":"Cannot query field \"hardware\" on type \"VehicleInformation\". Did you mean \"software\"?","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"hardware\" on type \"VehicleInformation\". Did you mean \"software\"?","    at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)","    at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)","    at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)","    at CTr (/var/task/src/functions/gateway/handler.js:48:24240)","    at c1r (/var/task/src/functions/gateway/handler.js:79:60144)","    at f (/var/task/src/functions/gateway/handler.js:287:40654)","    at zLr (/var/task/src/functions/gateway/handler.js:287:38973)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}},{"message":"Cannot query field \"claims\" on type \"VehicleInformation\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"claims\" on type \"VehicleInformation\".","    at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)","    at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)","    at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)","    at CTr (/var/task/src/functions/gateway/handler.js:48:24240)","    at c1r (/var/task/src/functions/gateway/handler.js:79:60144)","    at f (/var/task/src/functions/gateway/handler.js:287:40654)","    at zLr (/var/task/src/functions/gateway/handler.js:287:38973)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}},{"message":"Cannot query field \"performedClaims\" on type \"VehicleInformation\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"performedClaims\" on type \"VehicleInformation\".","    at Object.Field (/var/task/src/functions/gateway/handler.js:79:15305)","    at Object.enter (/var/task/src/functions/gateway/handler.js:48:25066)","    at Object.enter (/var/task/src/functions/gateway/handler.js:79:12424)","    at CTr (/var/task/src/functions/gateway/handler.js:48:24240)","    at c1r (/var/task/src/functions/gateway/handler.js:79:60144)","    at f (/var/task/src/functions/gateway/handler.js:287:40654)","    at zLr (/var/task/src/functions/gateway/handler.js:287:38973)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async qWe (/var/task/src/functions/gateway/handler.js:288:2270)"]}}}]}

**Comment by leeyuentuen** [comment]
same issue like this? https://github.com/leeyuentuen/polestar_api/issues/154

which version are you running?
