### ISSUE TITLE
Error 'unexpected error creating API' 

### ISSUE THREAD

**Issue by thriolsson** [leeyuentuen/polestar_api#23]
I am trying to add this integration for the first time.
I get the error 'Unexpected error adding the API' 
I can log in on Polestar web site and app using the same credentials.

How can I best troubleshoot this? 

![Screenshot_2023-12-21-08-48-04-93_c3a231c25ed346e59462e84656a70e50](https://github.com/leeyuentuen/polestar_api/assets/16080236/9fab4d9c-eeb8-4386-b0fb-80a701ca9cf1)

**Comment by leeyuentuen** [comment]
maybe take a look at the logs and see what log you can see

**Comment by thriolsson** [comment]
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/config_flow.py", line 47, in _create_device
    await device.init()
  File "/config/custom_components/polestar_api/polestar_api.py", line 51, in init
    'data': result['data']['getConsumerCarsV2'][0], 'timestamp': datetime.now()}
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by leeyuentuen** [comment]
i think duplicate error. https://github.com/leeyuentuen/polestar_api/issues/15

you don't have car in that account.
can you check if you have the full access on that account?

**Comment by thriolsson** [comment]
When I log in using my phone number, it work. 😊
But using my e-mail it does not work.
(On the web page and in the app both works)

**Comment by thriolsson** [comment]
When I log in using my phone number, it works. 😊
But using my e-mail does not work.
(On the web page and in the app both works)

**Comment by Borales** [comment]
When using version <1.2.0 (with the VIN setup form field) - it was working fine. Updating to the latest version doesn't break the app, but a clean install of 1.2.0 - gives the error below. 

<img width="421" alt="Screenshot 2023-12-25 at 21 04 09" src="https://github.com/leeyuentuen/polestar_api/assets/1118933/6d57113c-f8dc-485f-a2c4-d0e5fe47476d">
<img width="415" alt="Screenshot 2023-12-25 at 21 04 28" src="https://github.com/leeyuentuen/polestar_api/assets/1118933/cc3ddc53-6b22-4dfb-8090-e826c3d4a674">

**Comment by leeyuentuen** [comment]
> When using version <1.2.0 (with the VIN setup form field) - it was working fine. Updating to the latest version doesn't break the app, but a clean install of 1.2.0 - gives the error below.
> 
> <img alt="Screenshot 2023-12-25 at 21 04 09" width="421" src="https://private-user-images.githubusercontent.com/1118933/292777497-6d57113c-f8dc-485f-a2c4-d0e5fe47476d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MzY1MjAsIm5iZiI6MTcwMzUzNjIyMCwicGF0aCI6Ii8xMTE4OTMzLzI5Mjc3NzQ5Ny02ZDU3MTEzYy1mOGRjLTQ4NWYtYTJjNC1kMGU1ZmU0NzQ3NmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjVUMjAzMDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTk3NzE2NmJlN2Y0ZDhjNTVjMjczNWRiZTAzY2E3MjkyZmY3MmY4YTg5YjQzY2EwZmM1YjNhNDIzYzQyOTc3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RE14rKmLiWp3UZ-Y2QADNltYspGg9b2aeYPT-1OIiZU"> <img alt="Screenshot 2023-12-25 at 21 04 28" width="415" src="https://private-user-images.githubusercontent.com/1118933/292777498-cc3ddc53-6b22-4dfb-8090-e826c3d4a674.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MzY1MjAsIm5iZiI6MTcwMzUzNjIyMCwicGF0aCI6Ii8xMTE4OTMzLzI5Mjc3NzQ5OC1jYzNkZGM1My02YjIyLTRkZmItODA5MC1lODI2YzNkNGE2NzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjVUMjAzMDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODE1OWUwMTRmZTk4MDY4ZmU3NTBkN2YxYTQ4ZTdjNjczMTgyZDAzMWIwMWEzNTQ4OGQ5OTA3NmEwMDQwYzllMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bDvmy-9YHK-gqnYB0keva3BsJ0CQMIv8S7GVfktEUeo">

@Borales  thanks for report, should be fix on next public code:
https://github.com/leeyuentuen/polestar_api/releases/tag/1.2.1

**Comment by Borales** [comment]
@leeyuentuen checked 1.2.1 - that solved the problem for me, thanks!

**Comment by leeyuentuen** [comment]
i'll close this ticket, for issue, open a new one with logs for better follow up the problem.
