### ISSUE TITLE
Localization of sensors and values

### ISSUE THREAD

**Issue by bnordli** [leeyuentuen/polestar_api#28]
Sensors and values should be localizable. Currently the English names are hard coded in `sensors.py`, which makes them impossible to translate.

See https://developers.home-assistant.io/docs/internationalization/core/#entities for more information regarding this.

Excellent work, by the way, I have been waiting for something similar a long time! :1st_place_medal:

**Comment by leeyuentuen** [comment]
@bnordli they are now available in the beta version of 1.2.3, can you take a look?

**Comment by bnordli** [comment]
Looks great. I reviewed the Norwegian entity names in #54 .
