### ISSUE TITLE
No data from API - setup description wrong?

### ISSUE THREAD

**Issue by Ottmar0815** [leeyuentuen/polestar_api#3]
Hello,

thank you for developing this great integration!

I tried to do the descriped setup, but the integration couldn't receive any data.
In the logs (turned on debug-mode) there are some readings about fundamental issues:

> _2023-11-19 14:21:27.410 DEBUG (MainThread) [custom_components.polestar_api.polestar_api] Response <ClientResponse(https://volvoid.eu.volvocars.com/as/token.oauth2) [400 Bad Request]>
> 
> 2023-11-19 14:21:27.410 INFO (MainThread) [custom_components.polestar_api.polestar_api] Info API not available
> 
> 2023-11-19 14:21:27.459 DEBUG (MainThread) [custom_components.polestar_api.polestar_api] Response <ClientResponse(https://api.volvocars.com/energy/v1/vehicles/xxxxxxxxxxxx/recharge-status) [401 Unauthorized]>
> 
> 2023-11-19 14:21:27.501 DEBUG (MainThread) [custom_components.polestar_api.polestar_api] Response <ClientResponse(https://volvoid.eu.volvocars.com/as/token.oauth2) [400 Bad Request]>
> <CIMultiDictProxy('Date': 'Sun, 19 Nov 2023 13:21:27 GMT', 'x-frame-options': 'SAMEORIGIN', 'referrer-policy': 'origin', 'Cache-Control': 'no-cache, no-store', 'Pragma': 'no-cache', 'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'Content-Type': 'application/json;charset=utf-8', 'Set-Cookie': 'PF=q4ntGsQVy1ezvSWxjoIa9L; Path=/; Expires=Sun, 19-Nov-2023 14:21:27 GMT; Max-Age=3600; Secure; HttpOnly; SameSite=None', 'Server': 'vcc', 'Transfer-Encoding': 'chunked')>
> 
> 2023-11-19 14:21:27.501 INFO (MainThread) [custom_components.polestar_api.polestar_api] Info API not available_

I don't understand how the developer-account connects to the polestar account. How ist this working?
In the setup-description it states:

> Sign into your Polestar Account and go to your account: https://developer.volvocars.com/account/ Create a new Application. In my case it call 'My Polestar'

How could i sign into my polestar account and also sign in to the developer account?

Greetings

**Comment by leeyuentuen** [comment]
What i see here is first that it can't get the token. For the token you need an username and password.

i suppose your username and password is not correct, so they can't get your token to do the next step (getting car data)

**Comment by Ottmar0815** [comment]
I had testet both, my developer-credentials and my polestar-credentials at integration-setup.

In the description tbe developer-credentials should be used. Is this right? But then, how could data from polestar be received if there is no link from developer account to polestar.

**Comment by leeyuentuen** [comment]
indeed there is no link to your polestar needed. in theorie you can fetch any polestar with the vin

**Comment by stevelup** [comment]
The issue I've got is that I have no password to provide. The only option for signing up to the developer portal is with SSO via either GitHub or Google - so there is no password.

There doesn't seem to be any way to manually sign up with a user/pass.

**Comment by leeyuentuen** [comment]
try this website:

https://volvoid.eu.volvocars.com/VolvoLogin/login

**Comment by Ottmar0815** [comment]
In the German polestar forum there is a disscussion about that, yes.

But i saw in the api-description that it is also possible to get the position from the vehicle. Very dangerous i think.


Okay, back to topic:
With the developer credentials (for example with google login) used at integration-setup it should work?

**Comment by leeyuentuen** [comment]
let me know if it works and which step you have done

**Comment by Ottmar0815** [comment]
It works.
Steps:

1. Generated a Volvo-ID with your Link https://volvoid.eu.volvocars.com/VolvoLogin/login
2. Generated a Developer-Account with Google-Login.
3. Under developer account generate the app.
4. Get the 'vcc api key'.
5. Used HACS, add the repository and install the HACS-Integration.
6. Go to HomeAssistant integration and add polestar_api integration
7. Use the Volvo-ID credentials, your VIN and the developer 'vcc api key' at integration-setup in HomeAssistant.

Now Data are show instantly.

**Comment by stevelup** [comment]
> try this website:
> 
> https://volvoid.eu.volvocars.com/VolvoLogin/login

Hi

That worked perfectly - many thanks.

Steps as per @Ottmar0815 above.

The key was creating the Volvo ID and using that for the login credentials.

Regards,

Steve

**Comment by leeyuentuen** [comment]
@Ottmar0815 this issue can be closed? this has been solved?

**Comment by Ottmar0815** [comment]
Solved

**Comment by gwsfp** [comment]
Still confused on the login procedure. I have tried with Github-, Polestar- and Volvo login details, all with the same results. The API seems to connect succesfully, showing 8 entities. But all values are either false or unknown. Any idea what I am doing wrong here? The car does need to be part of the same network as HA, does it?

![image](https://github.com/leeyuentuen/polestar_api/assets/151539898/3f0d1b21-332b-43e6-aa78-1a4081596e9a)

**Comment by Ottmar0815** [comment]
> Still confused on the login procedure. I have tried with Github-, Polestar- and Volvo login details, all with the same results. The API seems to connect succesfully, showing 8 entities. But all values are either false or unknown. Any idea what I am doing wrong here? The car does not need to be part of the same network as HA, does it?
> 
> ![image](https://user-images.githubusercontent.com/151539898/284295029-3f0d1b21-332b-43e6-aa78-1a4081596e9a.png)

Try these steps:



> It works. Steps:
> 
> 1. Generated a Volvo-ID with your Link https://volvoid.eu.volvocars.com/VolvoLogin/login
> 2. Generated a Developer-Account with Google-Login.
> 3. Under developer account generate the app.
> 4. Get the 'vcc api key'.
> 5. Used HACS, add the repository and install the HACS-Integration.
> 6. Go to HomeAssistant integration and add polestar_api integration
> 7. Use the Volvo-ID credentials, your VIN and the developer 'vcc api key' at integration-setup in HomeAssistant.
> 
> Now Data are show instantly.

**Comment by leeyuentuen** [comment]
can you go to the integration and start the logging

![Screenshot 2023-11-20 at 15 32 51](https://github.com/leeyuentuen/polestar_api/assets/1487966/f79ced59-78e9-4074-92e7-352060d170ac)

**Comment by gwsfp** [comment]
> can you go to the integration and start the logging
> 
> ![Screenshot 2023-11-20 at 15 32 51](https://user-images.githubusercontent.com/1487966/284297240-f79ced59-78e9-4074-92e7-352060d170ac.png)

Okay, done. Also then removed integration entity and re-added it. Where should these log files now show?

**Comment by leeyuentuen** [comment]
it seems your token should got some issue, your username and password is not correct, so they can't get token. 

all other calls after token (with the vin) should be invalid due the token in incorrect

you can also  try use like post and use the below POST request

`https://volvoid.eu.volvocars.com/as/token.oauth2?grant_type=password&access_token_manager_id=JWTh4Yf0b&username=<username>&password=<password>&scope=openid email profile care_by_volvo:financial_information:invoice:read care_by_volvo:financial_information:payment_method care_by_volvo:subscription:read customer:attributes customer:attributes:write order:attributes vehicle:attributes tsp_customer_api:all conve:brake_status conve:climatization_start_stop conve:command_accessibility conve:commands conve:diagnostics_engine_status conve:diagnostics_workshop conve:doors_status conve:engine_status conve:environment conve:fuel_status conve:honk_flash conve:lock conve:lock_status conve:navigation conve:odometer_status conve:trip_statistics conve:tyre_status conve:unlock conve:vehicle_relation conve:warnings conve:windows_status energy:battery_charge_level energy:charging_connection_status energy:charging_system_status energy:electric_range energy:estimated_charging_time energy:recharge_status`


and replace the <username> and <password> with your username and password

and your response should look like on the screenshot
![image](https://github.com/leeyuentuen/polestar_api/assets/1487966/6b309281-ff83-429f-8104-410cd86ccb5d)

**Comment by leeyuentuen** [comment]
@gwsfp not sure, but seems volvo energy api is not working atm? see this issue:
https://github.com/leeyuentuen/polestar_api/issues/10

**Comment by gwsfp** [comment]
> @gwsfp not sure, but seems volvo energy api is not working atm? see this issue: #10

Ah, okay. Will stand by and fingers crossed.

**Comment by Ottmar0815** [comment]
Correct, it stopped working.
