### ISSUE TITLE
vin, registration_number and model_name become Unknown

### ISSUE THREAD

**Issue by jyrkih** [leeyuentuen/polestar_api#41]
those three fields are whitelisted in `get_skip_cache()`, thus excluding cache. However, there doesn't seem to be any refresh functionality either, thus becoming `None` pretty soon after init

**Comment by leeyuentuen** [comment]
the previous beta branch has incorrect logic, so that the reason why the get_skip_cache didn't work.

it was initially to use them to load once and not fetch them again

**Comment by Ottmar0815** [comment]
> it was initially to use them to load once and not fetch them again

Thats okay, but the data should remain.

**Comment by leeyuentuen** [comment]
@Ottmar0815 @jyrkih  does this still happen in the latest beta 1.2.9

**Comment by jyrkih** [comment]
no, not anymore!
