### ISSUE TITLE
"Issue creating API"

### ISSUE THREAD

**Issue by obot101** [leeyuentuen/polestar_api#59]
After submitting my login details it comes up withe the error "issue creating API, is there any known way of fixing this?

<img width="397" alt="Screenshot 2024-01-02 at 12 25 00" src="https://github.com/leeyuentuen/polestar_api/assets/112019174/2460d957-980b-46f3-b09f-98a168f33511">

**Comment by leeyuentuen** [comment]
can you check in the log what you get for error?
on which version are you using

could be a duplicated error like here: https://github.com/leeyuentuen/polestar_api/issues/43
