### ISSUE TITLE
Add Polestar in HA Brand repository

### ISSUE THREAD

**Issue by leeyuentuen** [leeyuentuen/polestar_api#6]

**Comment by stephanlarsson** [comment]
Already exists in HACS.

**Comment by dgomes** [comment]
Can't find it https://github.com/home-assistant/brands/tree/master/custom_integrations/polestar

**Comment by m0wlheld** [comment]
Did that for you: https://github.com/home-assistant/brands/pull/5012

**Comment by m0wlheld** [comment]
![grafik](https://github.com/leeyuentuen/polestar_api/assets/23745709/3fa3c6c8-b626-4143-a264-ece583f734b4)

The logo has been added to the brand repository. This issue may be closed as done.
