### ISSUE TITLE
Odometer is Reporting Wrong - Unit Conversion Error?

### ISSUE THREAD

**Issue by sembeeuk** [leeyuentuen/polestar_api#64]
Just updated to 1.3.4 and the Odometer values are wrong. 

sensor.polestar_XXX_current_odometer_meters

It is reporting my car has 37km. 

![image](https://github.com/leeyuentuen/polestar_api/assets/25618369/45c071af-c21e-4674-8f47-a60e701f7e3a)

Something gone wrong with the conversion changes made earlier?

**Comment by leeyuentuen** [comment]
will be fix soon

**Comment by leeyuentuen** [comment]
should fix here https://github.com/leeyuentuen/polestar_api/releases/tag/1.3.6
@sembeeuk  can you confirm?

**Comment by m0wlheld** [comment]
Nope, not fixed. 

![grafik](https://github.com/leeyuentuen/polestar_api/assets/23745709/582986fb-6a82-4295-a093-5ed361718ffd)

The 'state' of the sensor seems to be correct, according to the name it's odometer in meters. But the unit of measurement is set to kilometers, so the display is wrong.

![grafik](https://github.com/leeyuentuen/polestar_api/assets/23745709/545e50e1-bc89-4bde-b399-9d3be2d7b671)


Real  odometer value is 23,022 km

**Comment by sembeeuk** [comment]
I can confirm I am seeing the same thing - 37 million km.

**Comment by leeyuentuen** [comment]
should be fix in this beta: https://github.com/leeyuentuen/polestar_api/releases/tag/1.3.7

**Comment by sembeeuk** [comment]
That seems to have resolved the issue.
