### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by spockfish** [leeyuentuen/polestar_api#7]
The integration requires a username and password, but I've used Google as login partner, so there's no password.
What do I need to fill in?

**Comment by leeyuentuen** [comment]
see readme homepage:
![image](https://github.com/leeyuentuen/polestar_api/assets/1487966/7fe10be4-720e-4ca6-a9fe-611c68da9163)

if still issue, let me know

**Comment by spockfish** [comment]
Yeah, 

That update crossed my ticket creation.
Thanks, works now!
