### ISSUE TITLE
Polestar API UI not localised

### ISSUE THREAD

**Issue by m0wlheld** [leeyuentuen/polestar_api#70]
Hi,

my HA instance's UI is set to German / Germany. However, even since there is a German translation available, entity labels and state values are not displayed in German (see screenshot below). 

I am using HA Container installation and the Polestar API is manually installed as a custom component. It's the only custom component I use, so I don't know if HACS is required to apply the correct language.

![grafik](https://github.com/leeyuentuen/polestar_api/assets/23745709/d58c2ddf-e83a-468b-a9ec-78fbec924138)

**Comment by leeyuentuen** [comment]
strange that it is broken. need to investigate the reason for it. I thought it has work before.

**Comment by m0wlheld** [comment]
Please not: I am not using HACS but polestar_api as a custom component. Basically I copy `custom_components/polestar_api` to `$HA_HOME/config/custom_components/`.

**Comment by leeyuentuen** [comment]
> Please not: I am not using HACS but polestar_api as a custom component. Basically I copy `custom_components/polestar_api` to `$HA_HOME/config/custom_components/`.

yes i know, i test yesterday on development and it seems the same issue

**Comment by ohaue** [comment]
I have the same issue, but the translation works when setting up the integration:
<img width="284" alt="image" src="https://github.com/leeyuentuen/polestar_api/assets/63210219/fe7b93d8-9fd4-40f5-b8fd-292ef16a9bb1">

**Comment by leeyuentuen** [comment]
i'll take a look in the next days.

**Comment by leeyuentuen** [comment]
@ohaue @m0wlheld  can you take a look at this beta: https://github.com/leeyuentuen/polestar_api/releases/tag/1.5.3

I've tested on dutch and French (not all are translated yet)
![image](https://github.com/leeyuentuen/polestar_api/assets/1487966/3f2d7fbb-06b6-4bfd-96ff-e2b57f621fc3)
![image](https://github.com/leeyuentuen/polestar_api/assets/1487966/a7320e98-fad2-49ec-862c-90983d368da7)
![image](https://github.com/leeyuentuen/polestar_api/assets/1487966/bfd70fae-3d3a-4ea0-ad91-0ecd72ffef92)

**Comment by ohaue** [comment]
Seems to be working for most entities now. I have 5 entities - not translated (marked with red) but I can see that is because the entity names in my translation does not match :-)
<img width="246" alt="image" src="https://github.com/leeyuentuen/polestar_api/assets/63210219/44097d19-a481-4740-9fc3-8d9bde4af717">

**Comment by m0wlheld** [comment]
Works for German, with the exception of the 5 entity names from the comment above.

**Comment by leeyuentuen** [comment]
> Works for German, with the exception of the 5 entity names from the comment above.

it isn't translate due change of The native_unit_measurement. maybe i can fix all of them with find and replace

**Comment by ohaue** [comment]
I fixed the Danish translation and made a PR

**Comment by leeyuentuen** [comment]
> I fixed the Danish translation and made a PR

seems your branch is outdated. i'll check the PR later
