### ISSUE TITLE
bugfix: odometer

### ISSUE THREAD

**Issue by leeyuentuen** [leeyuentuen/polestar_api#74]
this should be wrong data from polestar
prevent this issue

maybe set max limit of 1.000.000

![Screenshot_2024-01-07-15-58-34-23_c3a231c25ed346e59462e84656a70e50](https://github.com/leeyuentuen/polestar_api/assets/1487966/54cb596b-6c54-4bea-b5d1-71de2130979b)

**Comment by leeyuentuen** [comment]
I've put a max limit to prevent to high value

**Comment by ScooterisT5** [comment]
Odometer has changed to unknown

**Comment by leeyuentuen** [comment]
open the entity and change them from m to km

i saw that i need to put the limit higher then 1000000

**Comment by ScooterisT5** [comment]
OK, confirmed. Switch to KM works as expected. Also if i change to Mi, and back.

**Comment by m0wlheld** [comment]
Confirmed. Works with  `m` and `km`. Does not work with `cm`, though ;) Is there really a need for a limit?

**Comment by leeyuentuen** [comment]
@m0wlheld As you see on the opening post image, sometimes, weird responses from Polestar make the graph go high

**Comment by m0wlheld** [comment]
> @m0wlheld As you see on the opening post image, sometimes, weird responses from Polestar make the graph go high

Speaking of which: The API currently reports 0 km (infact 600m) for the Odometer. It's the same for this HA integration and for the Polestar site. So - not a bug here.

![grafik](https://github.com/leeyuentuen/polestar_api/assets/23745709/746e79bf-5258-4a8e-a748-109cee9ec8de)

**Comment by m0wlheld** [comment]
It gets even better: Currently the API is reporting 2^31m, so the Odometer display 2.147.484 km ... looks like they are trying fix something.

**Comment by leeyuentuen** [comment]
> It gets even better: Currently the API is reporting 2^31m, so the Odometer display 2.147.484 km ... looks like they are trying fix something.

in the log? or showed in the gui that make spikes?

**Comment by m0wlheld** [comment]
It‘s reported wrong by the remote Polestar API. You cannot fix it.

**Comment by leeyuentuen** [comment]
> It‘s reported wrong by the remote Polestar API. You cannot fix it.

but this you saw the value on your home assistant gui? normally i have skip this high value

**Comment by leeyuentuen** [comment]
release at https://github.com/leeyuentuen/polestar_api/releases/tag/1.6.0
