### ISSUE TITLE
non-metric conversions not all working

### ISSUE THREAD

**Issue by carrel-gr** [leeyuentuen/polestar_api#76]
It seems that the average speed, odometer, and energy consumption values are not working in non-metric mode.  The first two are just minor fixes.  The third is a math error.  I have a patch that works.  If given permission, I'll open a pull request.
[polestar_api_diff.txt](https://github.com/leeyuentuen/polestar_api/files/13854903/polestar_api_diff.txt)

**Comment by leeyuentuen** [comment]
duplicated: https://github.com/leeyuentuen/polestar_api/issues/72
