### ISSUE TITLE
Range value higher than max value

### ISSUE THREAD

**Issue by Birdman86** [leeyuentuen/polestar_api#84]
Getting this error in the log:
Read Timeout on update data
estimate_range: Value 1018 is higher than max value 660
estimate_full_charge_range: Value 1018 is higher than max value 660

On version 1.5.1.
Just updated to 1.5.4 to see if this will be fixed.

**Comment by Birdman86** [comment]
My P2 is never getting anywhere near 660, so I don't know where it got the value of 1018.
Maybe it is 101.8 km, but that sounds too low as well considering its SOC is on 49%

**Comment by leeyuentuen** [comment]
> My P2 is never getting anywhere near 660, so I don't know where it got the value of 1018. Maybe it is 101.8 km, but that sounds too low as well considering its SOC is on 49%

it is just sometimes with weird value. if you open polestar app, it will maybe force them to update, otherwise try to reboot the polestar console (in car) by pressing the center down of your screen (3times) it will force to reload some data

**Comment by Birdman86** [comment]
Tried forcing the app and rebooting the console, still same error.

**Comment by Trnquill** [comment]
It does that every now and then. The same incorrect value can be seen on polestar.com, too. It usually goes away quite fast with no action from customer side and is then back to normal. Some internal error value at Polestar end, maybe?

**Comment by leeyuentuen** [comment]
i'll close this issue, if still exists, you can reopen
