### ISSUE TITLE
Unable to use some sensor values in automations

### ISSUE THREAD

**Issue by RobDemandt** [leeyuentuen/polestar_api#89]
It appears only the sensor values that are numerical can be used in automations. The possible states of other sensor values cannot be selected (example: connection status = connected or not connected)

**Comment by leeyuentuen** [comment]
i'll take a look on it

**Comment by VdR1960** [comment]
Automations based on the 'connection status' and also the 'charging status' has always worked for me. A recent update caused all entity IDs to be changed ( '_2'  was appended to the entity IDs). This caused the automations to break. Updating the entity names in the automations has fixed the issue.

Maybe this observation helps.

**Comment by leeyuentuen** [comment]
@RobDemandt  is the answer above fix your issue? or should this be investigated?
