### ISSUE TITLE
API not work with Australia VIN

### ISSUE THREAD

**Issue by BeauGiles** [leeyuentuen/polestar_api#9]
Hi!
Excited to see this is finally a thing - however I can't get it to work.

Got my Volvo ID, API key and Polestar VIN set up - but it never loads.
With debug logging in, I get this in my logs

`2023-11-20 08:10:19.489 DEBUG (MainThread) [custom_components.polestar_api.polestar_api] Response {'status': 200, 'operationId': 'cb2ffcaa-XXXX-XXXX-XXXX-0d26308bd47e', 'data': {}}
2023-11-20 08:10:19.490 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up polestar_api platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/polestar_api/sensor.py", line 184, in async_setup_entry
    sensors = [
              ^
  File "/config/custom_components/polestar_api/sensor.py", line 185, in <listcomp>
    PolestarSensor(device, description) for description in POLESTAR_SENSOR_TYPES
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/sensor.py", line 215, in __init__
    self._async_update_attrs()
  File "/config/custom_components/polestar_api/sensor.py", line 225, in _async_update_attrs
    self._attr_native_value = self._device.get_cache_data(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/polestar_api.py", line 87, in get_cache_data
    data = data[key]
           ~~~~^^^^^
KeyError: 'batteryChargeLevel'
`

Are you using the Energy API (https://developer.volvocars.com/apis/energy/v1/overview/)?
It is only available in certain countries

> The API can be used with test credentials around the world. However, when published, only cars in the Europe / Middle East / Africa regions are available. We are working to bring other regions online.
View the full list of available countries [here](https://developer.volvocars.com/terms-and-conditions/apis-supported-locations/)

(this also applies to Volvo Cars - eg an XC40 in Australia has no access to the Energy API, however there must be another way to access the data - this volvo2mqtt integration works in Australia without the Energy status https://github.com/Dielee/volvo2mqtt)

**Comment by leeyuentuen** [comment]
from you profile, i saw you are from spain. i suppose spain in also in the list?

**Comment by BeauGiles** [comment]
Australia (the .es in my domain is part of my last name)

**Comment by leeyuentuen** [comment]
> Australia (the .es in my domain is part of my last name)

do you mind sending your vin in PM, so I can take a look if it on VIN limitation or account limitation

**Comment by leeyuentuen** [comment]
i've investigated, I'm using my volvo account and fetching the vin, 
I got no data back , so I think the vin is 'block' by volvo API.
![image](https://github.com/leeyuentuen/polestar_api/assets/1487966/8e53a836-eb0b-435f-96da-269441e9cf9a)

**Comment by leeyuentuen** [comment]
@BeauGiles can you test the new release and see if your car information can be read?
https://github.com/leeyuentuen/polestar_api/releases/tag/1.0.1

**Comment by BeauGiles** [comment]
> @BeauGiles can you test the new release and see if your car information can be read? https://github.com/leeyuentuen/polestar_api/releases/tag/1.0.1

Works fine :)
