### ISSUE TITLE
Average energy consumption entity is always the same

### ISSUE THREAD

**Issue by ohaue** [leeyuentuen/polestar_api#91]
Am I the only one that always has the same value in "average_energy_consumption_kwh_per_100" ?

The value for me is always "24"
![image](https://github.com/leeyuentuen/polestar_api/assets/63210219/a52c4ee9-f87b-4e96-a05a-60c2080cae60)

**Comment by leeyuentuen** [comment]
![Screenshot_2024-01-13-17-36-23-84_c3a231c25ed346e59462e84656a70e50](https://github.com/leeyuentuen/polestar_api/assets/1487966/142a071b-e5a0-4c40-b8de-48ba64c8fa1d)

this is mine one

**Comment by kristoferericsson** [comment]
Does not change for me either
![IMG_8475](https://github.com/leeyuentuen/polestar_api/assets/75800858/ac1d06bd-d08e-4f1f-9fda-9d9e159096c5)

**Comment by wouterhardeman** [comment]
That's because it's based on the manual trip odometer. I've reset it and got this.
![image](https://github.com/leeyuentuen/polestar_api/assets/495620/70f38dd7-57f5-47f5-b4df-ee020c466648)

**Comment by leeyuentuen** [comment]
i'll close this issue, if still exists, just reopen it
