### ISSUE TITLE
Delayed battery sensor values

### ISSUE THREAD

**Issue by MKr82** [leeyuentuen/polestar_api#93]
When I drive my car, the battery percentage is (of course) dropping during the trip. 
This is more or less directly visible in the official Polestar app, but not in the Polestar API. 
Sometimes there is a delay upto 1,5 hours before sensor value of battery percentage is changing.

So when I drive home between 17:00 and 18:00, I see the battery percentage change during a period between 18:20 to 19:20. So I see my battery percentage dropping when I am sitting on the dinner table...

For the ODO meter there is no delay btw.

**Comment by leeyuentuen** [comment]
i notice that there is a delay. in the website the  value is also not changed. only on the app i see a difference. i think this is not from the code issue, but issue on the polestar side (i think they use some caching to prevent DDoS)

**Comment by MKr82** [comment]
Did not check the website, but I agree: seems to be caused by Polestar side.
Thanks for the confirmation.
