### ISSUE TITLE
Polestar API Down: New API Endpoint "/mystar-v2"

### ISSUE THREAD

**Issue by leeyuentuen** [leeyuentuen/polestar_api#96]
### Discussed in https://github.com/leeyuentuen/polestar_api/discussions/95

<div type='discussions-op-text'>

<sup>Originally posted by **loebse** January 18, 2024</sup>
Looks like there is a new API endpoint available. 

The "old" ``/my-star`` is no longer working. However, there is a new one ``/mystar-v2``</div>

**Comment by wouterhardeman** [comment]
It appears that getBatteryData and getOdometerData have been moved to `mystar-v2`. Queries like getConsumerCarsV2 are still in `/my-star`

![image](https://github.com/leeyuentuen/polestar_api/assets/495620/a5bf4ee1-e6ad-4025-9b5c-c72e413405c2)

**Comment by leeyuentuen** [comment]
@wouterhardeman  should work on the new beta version, can you check the message above?

**Comment by mountainbikert** [comment]
I just checked 1.57, but Odometer value is way off now. Instead of 8000 I now have 8.000.000 km

**Comment by mountainbikert** [comment]
All entities are back up again. There's also a new (static) value: Torque

**Comment by leeyuentuen** [comment]
> All entities are back up again. There's also a new (static) value: Torque

ya, I was planning to do something, but it seems it doesn't work.
I want to calculate the charging speed, but I need to know the battery size (what I have) I don't know what the battery limit is set atm. so I can't continue

**Comment by wouterhardeman** [comment]
> > All entities are back up again. There's also a new (static) value: Torque
> 
> ya, I was planning to do something, but it seems it doesn't work. I want to calculate the charging speed, but I need to know the battery size (what I have) I don't know what the battery limit is set atm. so I can't continue

You could make an estimate by using the time delta between battery percentage going up and then diving that by the battery size. I could have a try and implement it if you want?

**Comment by leeyuentuen** [comment]
> > > All entities are back up again. There's also a new (static) value: Torque
> > 
> > 
> > ya, I was planning to do something, but it seems it doesn't work. I want to calculate the charging speed, but I need to know the battery size (what I have) I don't know what the battery limit is set atm. so I can't continue
> 
> You could make an estimate by using the time delta between battery percentage going up and then diving that by the battery size. I could have a try and implement it if you want?

be my guest to try it out. not sure how accurate the delta time will be, because sometimes it only updates every 5 min or something.

**Comment by leeyuentuen** [comment]
i'll close this issue, for more discussion, we can continue on disuccion https://github.com/leeyuentuen/polestar_api/discussions/95

**Comment by andig** [comment]
Have just hit the same in https://github.com/evcc-io/evcc/issues/11754. Followed your change, i.e. use `/mystar-v2` for battery and odometer. Unfortunately, I'm seeing 

```
{
  "errors" : [ {
    "errorType" : "UnauthorizedException",
    "message" : "Unauthorized"
  } ]
}
```

for the new endpoint, using identical token as for the original endpoint. Did you notice anything like this?

**Comment by leeyuentuen** [comment]
> Have just hit the same in [evcc-io/evcc#11754](https://github.com/evcc-io/evcc/issues/11754). Followed your change, i.e. use `/mystar-v2` for battery and odometer. Unfortunately, I'm seeing
> 
> ```
> {
>   "errors" : [ {
>     "errorType" : "UnauthorizedException",
>     "message" : "Unauthorized"
>   } ]
> }
> ```
> 
> for the new endpoint, using identical token as for the original endpoint. Did you notice anything like this?

depends which call you get this exception. the call
the odo and battery call it is only the url

the other getcarinformation add extra variable to locale

**Comment by andig** [comment]
Only odo and battery. Maybe I‘ll need to test with different car to see if that makes a difference. Thank you!

**Comment by andig** [comment]
Btw, https://github.com/leeyuentuen/polestar_api/commit/aa88faf730b03bb3f67a702f70eb948acd884a93#diff-6c13acca0123ef6e56fd0bfc79573379cde1a7f9a1cd556b39f9a301cfdebfeeR106 looks wrong- local instead of locale? But still works?

**Comment by leeyuentuen** [comment]
> Only odo and battery. Maybe I‘ll need to test with different car to see if that makes a difference. Thank you!



> Btw, [aa88faf#diff-6c13acca0123ef6e56fd0bfc79573379cde1a7f9a1cd556b39f9a301cfdebfeeR106](https://github.com/leeyuentuen/polestar_api/commit/aa88faf730b03bb3f67a702f70eb948acd884a93#diff-6c13acca0123ef6e56fd0bfc79573379cde1a7f9a1cd556b39f9a301cfdebfeeR106) looks wrong- local instead of locale? But still works?

nice, maybe it should filled in to get work. but i'll change them next time

**Comment by leeyuentuen** [comment]
i'll check later. i'm not at my pc today

**Comment by leeyuentuen** [comment]
@andig  it works for me 
![image](https://github.com/leeyuentuen/polestar_api/assets/1487966/3dceaaaf-c9c6-427a-b29d-521ff98bdc7e)

using the following curl call:
`curl -X POST --data '{"query":"query getCars{getConsumerCarsV2{vin,internalVehicleIdentifier}}","operationName":"getCars"}' \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $token" \
https://pc-api.polestar.com/eu-north-1/my-star`

`curl -X POST --data '{"query":"query GetOdometerData($vin:String!){getOdometerData(vin:$vin){averageSpeedKmPerHour eventUpdatedTimestamp{iso unix}odometerMeters tripMeterAutomaticKm tripMeterManualKm}}","variables":{"vin”:”<vin>"},"operationName":"GetOdometerData"}' \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $token" \
https://pc-api.polestar.com/eu-north-1/mystar-v2`

**Comment by andig** [comment]
Thank you, much appreciated. Seems there are further implementation differences that I'll need to figure out.

**Comment by andig** [comment]
@leeyuentuen additional difference I've found is authentication. Seems you're using the flow that the web app is using while I was using a different flow for `polexplore`. Could I kindly ask you to share a `curl` example for `getAuthToken` graphQL? For some weird reason I always bump into " `BAD USER INPUT` and I'm still unsure if really all vehicles should work for the new auth of if this is maybe a weird firmware-difference thing. Much appreciated!

**Comment by leeyuentuen** [comment]
i haven't use in this api the getAuthToken. but the graphql should be like this:

`query GetAuthToken($code: String) {
  getAuthToken(code: $code) {
    access_token
    refresh_token
    id_token
    expires_in
  }
}`

**Comment by leeyuentuen** [comment]
by the way, it would be interesting if you were using polexplore. on my API version here I'm using polmystar

if you have token from polexplore, then you should also get access on the climate and the door unlock feature I suppose

**Comment by leeyuentuen** [comment]
@andig  maybe easier to continue in the discussion thread? https://github.com/leeyuentuen/polestar_api/discussions/95
because is not really an issue  but more a discussion
