### ISSUE TITLE
Odometer value is filtered out even though it seems correct

### ISSUE THREAD

**Issue by olalid** [leeyuentuen/polestar_api#99]
My odometer sensor does not work anymore (it used to work in earlier versions but I am now using 1.6.1).
I get following message in the log:
WARNING (MainThread) [custom_components.polestar_api.sensor] current_odometer: Value 105860104 is higher than max value 100000000
But the value seems to be correct, 105860104 seems to be in meters ('odometerMeters': 105860104), and the odometer of my car shows 105860 km currently, i.e. that value divided by 1000.

**Comment by leeyuentuen** [comment]
i'll put the max limit higher, but i need to check that we won't spike

**Comment by leeyuentuen** [comment]
can you take a look at this beta version?
https://github.com/leeyuentuen/polestar_api/releases/tag/1.6.2

**Comment by olalid** [comment]
Yes, works for me.

**Comment by leeyuentuen** [comment]
released 1.6.3
